# Generated by Django 3.2.4 on 2021-07-07 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210705_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='type',
            field=models.CharField(default='Tree', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('servings', models.IntegerField()),
                ('preptime', models.CharField(max_length=50)),
                ('cooktime', models.CharField(max_length=50)),
                ('ingredients', models.TextField(max_length=250)),
                ('directions', models.TextField(max_length=1000)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.plant')),
            ],
        ),
    ]
